# Generated by Django 4.2.1 on 2026-04-27 12:01

from django.db import migrations, models


def create_unmanaged_price_tables(apps, schema_editor):
    connection = schema_editor.connection
    vendor = connection.vendor
    id_type = "BIGINT PRIMARY KEY AUTO_INCREMENT" if vendor == "mysql" else "INTEGER PRIMARY KEY AUTOINCREMENT"
    bool_type = "BOOLEAN" if vendor == "mysql" else "INTEGER"

    with connection.cursor() as cursor:
        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS iteminfo (
                id {id_type},
                appid VARCHAR(8) NULL,
                name VARCHAR(128) NULL,
                market_hash_name VARCHAR(128) NOT NULL,
                market_name_cn VARCHAR(128) NULL,
                icon_url VARCHAR(512) NULL,
                quality VARCHAR(64) NULL,
                quality_color VARCHAR(32) NULL,
                collection VARCHAR(64) NULL,
                collection_url VARCHAR(512) NULL,
                category VARCHAR(50) NULL
            )
            """
        )
        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS price (
                id {id_type},
                iteminfo_id BIGINT NULL UNIQUE,
                buff_id INTEGER NULL,
                buff_buy_price DECIMAL(8, 2) NULL,
                buff_buy_num INTEGER NULL,
                buff_sell_price DECIMAL(8, 2) NULL,
                buff_sell_num INTEGER NULL,
                buff_time DATETIME NULL,
                steam_price DECIMAL(8, 2) NULL,
                steam_price_cny DECIMAL(8, 2) NULL,
                steam_time DATETIME NULL,
                wax_price DECIMAL(15, 2) NULL,
                wax_time DATETIME NULL,
                wax_count INTEGER NULL,
                shadow_price DECIMAL(8, 2) NULL,
                shadow_time DATE NULL,
                shadow_sell_num INTEGER NULL,
                stock INTEGER NULL DEFAULT 0,
                star {bool_type} NULL,
                cent DOUBLE NOT NULL DEFAULT 0,
                profit DECIMAL(8, 2) NULL,
                card_price DECIMAL(8, 2) NULL,
                wax_avg_sells INTEGER NULL DEFAULT 0,
                c5_price DECIMAL(8, 2) NULL,
                ig_price DECIMAL(8, 2) NULL,
                uu_price DECIMAL(8, 2) NULL
            )
            """
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Iteminfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appid", models.CharField(blank=True, max_length=8, null=True)),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                ("market_hash_name", models.CharField(max_length=128)),
                (
                    "market_name_cn",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("icon_url", models.CharField(blank=True, max_length=512, null=True)),
                ("quality", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "quality_color",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("collection", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "collection_url",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "iteminfo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buff_id", models.IntegerField(blank=True, null=True)),
                (
                    "buff_buy_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("buff_buy_num", models.IntegerField(blank=True, null=True)),
                (
                    "buff_sell_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("buff_sell_num", models.IntegerField(blank=True, null=True)),
                ("buff_time", models.DateTimeField(blank=True, null=True)),
                (
                    "steam_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "steam_price_cny",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("steam_time", models.DateTimeField(blank=True, null=True)),
                (
                    "wax_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("wax_time", models.DateTimeField(blank=True, null=True)),
                ("wax_count", models.IntegerField(blank=True, null=True)),
                (
                    "shadow_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("shadow_time", models.DateField(blank=True, null=True)),
                ("shadow_sell_num", models.IntegerField(blank=True, null=True)),
                ("stock", models.IntegerField(blank=True, default=0, null=True)),
                ("star", models.BooleanField(blank=True, null=True)),
                ("cent", models.FloatField(default=0, verbose_name="cent")),
                (
                    "profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "card_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "wax_avg_sells",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "c5_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "ig_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "uu_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
            options={
                "db_table": "price",
                "managed": False,
            },
        ),
        migrations.RunPython(create_unmanaged_price_tables, migrations.RunPython.noop),
    ]
