# Generated by Django 4.2.1 on 2026-04-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iteminfo",
            options={},
        ),
        migrations.AlterModelOptions(
            name="price",
            options={},
        ),
    ]
