# Generated by Django 4.2.1 on 2026-04-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0003_price_state_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArbitrageOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direction_a_platform", models.CharField(max_length=32)),
                ("direction_a_platform_label", models.CharField(max_length=64)),
                ("direction_a_group", models.CharField(max_length=32)),
                (
                    "direction_a_price_cny",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "direction_a_source_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("direction_a_source_currency", models.CharField(max_length=8)),
                ("direction_a_volume", models.IntegerField(default=0)),
                ("direction_b_platform", models.CharField(max_length=32)),
                ("direction_b_platform_label", models.CharField(max_length=64)),
                ("direction_b_group", models.CharField(max_length=32)),
                (
                    "direction_b_price_cny",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "direction_b_source_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("direction_b_source_currency", models.CharField(max_length=8)),
                ("direction_b_volume", models.IntegerField(default=0)),
                (
                    "direction_b_fee_rate",
                    models.DecimalField(decimal_places=4, max_digits=6),
                ),
                (
                    "direction_b_net_cny",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("profit_cny", models.DecimalField(decimal_places=2, max_digits=12)),
                ("margin_pct", models.DecimalField(decimal_places=2, max_digits=8)),
                ("usd_cny_rate", models.DecimalField(decimal_places=4, max_digits=8)),
                ("min_volume", models.IntegerField(default=1)),
                ("calculation_batch_id", models.CharField(max_length=36)),
                ("calculated_at", models.DateTimeField()),
                (
                    "iteminfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arbitrage_opportunities",
                        to="price.iteminfo",
                    ),
                ),
            ],
            options={
                "db_table": "arbitrage_opportunity",
                "indexes": [
                    models.Index(
                        fields=["-profit_cny"], name="arbitrage_o_profit__c3a39b_idx"
                    ),
                    models.Index(
                        fields=["direction_a_platform", "direction_b_platform"],
                        name="arbitrage_o_directi_b99a78_idx",
                    ),
                    models.Index(
                        fields=["calculated_at"], name="arbitrage_o_calcula_ab922a_idx"
                    ),
                    models.Index(
                        fields=["margin_pct"], name="arbitrage_o_margin__d0f5a9_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="arbitrageopportunity",
            constraint=models.UniqueConstraint(
                fields=("iteminfo", "direction_a_platform", "direction_b_platform"),
                name="uniq_arbitrage_item_direction",
            ),
        ),
    ]
