# Generated by Django 4.2.1 on 2026-04-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0004_add_arbitrage_opportunity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="profit",
        ),
    ]
