# Generated by Django 4.2.1 on 2026-04-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0005_remove_price_profit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPlatformListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=32)),
                ("platform_item_id", models.CharField(max_length=80)),
                (
                    "source_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "iteminfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_listings",
                        to="price.iteminfo",
                    ),
                ),
            ],
            options={
                "db_table": "item_platform_listing",
                "indexes": [
                    models.Index(
                        fields=["platform", "platform_item_id"],
                        name="item_platfo_platfor_94e57d_idx",
                    ),
                    models.Index(
                        fields=["platform"], name="item_platfo_platfor_f406af_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="itemplatformlisting",
            constraint=models.UniqueConstraint(
                fields=("iteminfo", "platform"), name="uniq_item_platform_listing"
            ),
        ),
    ]
