# Generated by Django 4.2.1 on 2026-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0006_add_item_platform_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitrageopportunity",
            name="direction_a_quotes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="arbitrageopportunity",
            name="direction_b_quotes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
