# Generated by Django 4.2.1 on 2026-04-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0007_add_arbitrage_direction_quotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="uu_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
