# Generated by Django 4.2.1 on 2026-04-27 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("price", "0008_price_uu_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direction_a_platform", models.CharField(max_length=32)),
                ("direction_b_platform", models.CharField(max_length=32)),
                ("buy_price_cny", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "sell_price_cny",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "sell_fee_cny",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_cost_cny",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "realized_profit_cny",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("traded_at", models.DateTimeField()),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "iteminfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_records",
                        to="price.iteminfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trade_record",
                "indexes": [
                    models.Index(
                        fields=["user", "-traded_at"],
                        name="trade_recor_user_id_eebcae_idx",
                    ),
                    models.Index(
                        fields=["iteminfo", "-traded_at"],
                        name="trade_recor_iteminf_882660_idx",
                    ),
                    models.Index(
                        fields=["direction_a_platform", "direction_b_platform"],
                        name="trade_recor_directi_677279_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OpportunityFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direction_a_platform", models.CharField(max_length=32)),
                ("direction_b_platform", models.CharField(max_length=32)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "iteminfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_favorites",
                        to="price.iteminfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "opportunity_favorite",
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="opportunity_user_id_115f3e_idx",
                    ),
                    models.Index(
                        fields=[
                            "iteminfo",
                            "direction_a_platform",
                            "direction_b_platform",
                        ],
                        name="opportunity_iteminf_a46305_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="opportunityfavorite",
            constraint=models.UniqueConstraint(
                fields=(
                    "user",
                    "iteminfo",
                    "direction_a_platform",
                    "direction_b_platform",
                ),
                name="uniq_user_opportunity_favorite",
            ),
        ),
    ]
