# Generated by Django 4.2.1 on 2026-04-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0009_traderecord_opportunityfavorite_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=32)),
                ("platform_label", models.CharField(max_length=64)),
                ("price_cny", models.DecimalField(decimal_places=2, max_digits=12)),
                ("source_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("source_currency", models.CharField(max_length=8)),
                ("volume", models.IntegerField(default=0)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("captured_at", models.DateTimeField()),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "iteminfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_snapshots",
                        to="price.iteminfo",
                    ),
                ),
            ],
            options={
                "db_table": "price_snapshot",
                "indexes": [
                    models.Index(
                        fields=["iteminfo", "platform", "captured_at"],
                        name="price_snaps_iteminf_dde7ec_idx",
                    ),
                    models.Index(
                        fields=["platform", "captured_at"],
                        name="price_snaps_platfor_e0d4fe_idx",
                    ),
                    models.Index(
                        fields=["iteminfo", "-captured_at"],
                        name="price_snaps_iteminf_0d8da4_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pricesnapshot",
            constraint=models.UniqueConstraint(
                fields=("iteminfo", "platform", "captured_at"),
                name="uniq_price_snapshot_item_platform_time",
            ),
        ),
    ]
