# Generated by Django 4.2.1 on 2026-04-27 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPlatformChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("is_completed", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_checklist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_completed"],
                        name="authuser_us_user_id_625197_idx",
                    ),
                    models.Index(fields=["key"], name="authuser_us_key_3d730b_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userplatformchecklist",
            constraint=models.UniqueConstraint(
                fields=("user", "key"), name="uniq_user_platform_checklist_key"
            ),
        ),
    ]
