# Generated by Django 4.2.1 on 2026-04-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0002_userplatformchecklist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="steam_avatar",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_avatar_full",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_avatar_medium",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_comment_permission",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_community_visibility_state",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_last_logoff",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_loc_city_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_loc_country_code",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_loc_state_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_openid_claimed_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_openid_identity",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_openid_raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_persona_state",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_persona_state_flags",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_primary_clan_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_profile_raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_profile_state",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_profile_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_profile_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_real_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steam_time_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
