# Generated by Django 4.2.1 on 2026-04-28 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authuser", "0003_userprofile_steam_avatar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSteamInventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steam_id", models.CharField(db_index=True, max_length=32)),
                ("appid", models.CharField(default="730", max_length=16)),
                ("contextid", models.CharField(default="2", max_length=16)),
                ("assetid", models.CharField(max_length=64)),
                ("classid", models.CharField(blank=True, max_length=64)),
                ("instanceid", models.CharField(blank=True, max_length=64)),
                ("amount", models.PositiveIntegerField(default=1)),
                (
                    "market_hash_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("market_name", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("name_color", models.CharField(blank=True, max_length=32)),
                ("type", models.CharField(blank=True, max_length=128)),
                ("icon_url", models.CharField(blank=True, max_length=512)),
                ("tradable", models.BooleanField(default=False)),
                ("marketable", models.BooleanField(default=False)),
                ("commodity", models.BooleanField(default=False)),
                ("inspect_url", models.CharField(blank=True, max_length=512)),
                ("exterior", models.CharField(blank=True, max_length=64)),
                ("raw_asset", models.JSONField(blank=True, default=dict)),
                ("raw_description", models.JSONField(blank=True, default=dict)),
                ("raw_properties", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("synced_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steam_inventory_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_steam_inventory_item",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active", "-synced_at"],
                        name="user_steam__user_id_bb94d3_idx",
                    ),
                    models.Index(
                        fields=["steam_id", "appid", "contextid"],
                        name="user_steam__steam_i_96022f_idx",
                    ),
                    models.Index(
                        fields=["market_hash_name"],
                        name="user_steam__market__410d35_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="usersteaminventoryitem",
            constraint=models.UniqueConstraint(
                fields=("user", "appid", "contextid", "assetid"),
                name="uniq_user_steam_inventory_asset",
            ),
        ),
    ]
